version: "3.8"

services:
  db:
    image: postgres:14
    container_name: splitpay_db
    environment:
      POSTGRES_DB: splitpay
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: splitpay_api
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/code

volumes:
  db_data:
